# Generated by Django 5.2.1 on 2025-06-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_alter_record_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
