# Generated by Django 5.2.1 on 2025-06-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_record_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
