# Generated by Django 5.2.1 on 2025-07-28 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('profile_picture_url', models.ImageField(blank=True, null=True, upload_to='artist_img')),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='apiApp.artist'),
        ),
    ]
