# Generated by Django 5.2.1 on 2025-07-28 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0006_artist_alter_record_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='genre',
        ),
        migrations.AddField(
            model_name='record',
            name='genere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='apiApp.genere'),
        ),
    ]
