# Generated by Django 5.2.1 on 2025-08-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0007_genere_remove_record_genre_record_genere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='cover_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
