# Generated by Django 5.2.1 on 2025-11-26 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0014_rename_added_at_wishlist_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('wishlist', 'record')},
        ),
    ]
