# Generated by Django 5.2.1 on 2025-11-28 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0016_user_profile_picture_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordRatingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_summary', to='apiApp.record')),
            ],
        ),
    ]
