# Generated by Django 5.2.1 on 2025-12-03 09:12

import apiApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0019_cart_user_record_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default=apiApp.models.generate_cart_code, max_length=100, unique=True),
        ),
    ]
