# Generated by Django 5.2.1 on 2025-12-06 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0021_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
