# Generated by Django 5.2.1 on 2025-12-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0022_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='items_inside',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='record',
            name='release_date',
            field=models.PositiveIntegerField(blank=True, default=2025, null=True),
        ),
    ]
