# Generated by Django 5.2.1 on 2025-12-06 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0023_record_items_inside_alter_record_release_date'),
    ]

    operations = [
    ]
