# Generated by Django 5.2.1 on 2025-12-06 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0025_auto_20251206_0151'),
    ]

    operations = [
    ]
