# Generated by Django 5.2.1 on 2025-12-06 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0024_auto_20251206_0146'),
        ('apiApp', '0026_auto_20251206_0152'),
    ]

    operations = [
    ]
