# Generated by Django 5.2.1 on 2025-12-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0028_add_items_inside'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='profile_picture_url',
        ),
        migrations.AlterField(
            model_name='record',
            name='release_date',
            field=models.PositiveIntegerField(blank=True, default=2025, null=True),
        ),
    ]
