# Generated by Django 5.2.1 on 2025-12-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0029_remove_artist_bio_remove_artist_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
