# Generated by Django 5.2.1 on 2025-12-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0030_user_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped_to',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
