# Generated by Django 5.2.1 on 2026-01-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0031_order_shipped_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
