# Generated by Django 5.2.1 on 2026-01-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0032_order_shipping_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ship_link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
