# Generated by Django 5.2.1 on 2026-01-04 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0033_order_ship_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
