# Generated by Django 5.2.1 on 2026-01-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0034_fix_order_amounts'),
        ('apiApp', '0034_remove_user_profile_picture'),
    ]

    operations = [
    ]
