# Generated by Django 5.2.1 on 2026-08-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0035_merge_20260113_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
