# Generated by Django 5.2.1 on 2026-08-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0037_mark_existing_users_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=10),
        ),
    ]
