# Generated by Django 5.2.1 on 2026-08-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0040_populate_record_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='final_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
