# Generated by Django 5.2.1 on 2026-08-21 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0042_rename_ship_link_order_shipping_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiApp.record'),
        ),
    ]
