# Generated by Django 5.2.1 on 2026-08-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0043_alter_orderitem_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bazares/%Y/%m/')),
                ('date', models.DateField()),
                ('schedule', models.CharField(blank=True, default='', help_text="e.g. '10:00 am - 6:00 pm'", max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('google_maps_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
