# Generated by Django 5.2.1 on 2026-08-24 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0044_bazar'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_bazar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='apiApp.bazar'),
        ),
    ]
