# Generated by Django 5.2.1 on 2026-08-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0046_backfill_sell_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
    ]
