# Generated by Django 5.2.1 on 2026-09-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0047_siteconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('access_admin_panel', 'Acceder a Administración'), ('tab_add_record', 'Ver pestaña Agregar disco'), ('tab_manage_records', 'Ver pestaña Gestionar discos'), ('tab_manage_bazares', 'Ver pestaña Manejo de bazares'), ('tab_manage_orders', 'Ver pestaña Pedidos'), ('tab_manage_users', 'Ver pestaña Gestionar usuarios')]},
        ),
    ]
