# Generated by Django 5.2.1 on 2026-09-29 07:48

from decimal import Decimal
from django.db import migrations, models


def backfill_existing_sales(apps, schema_editor):
    """Sales before this migration: no commission, so final price = items subtotal;
    snapshot each item's record so receipts can be reprinted."""
    Sale = apps.get_model('apiApp', 'Sale')
    SaleItem = apps.get_model('apiApp', 'SaleItem')
    for item in SaleItem.objects.select_related('record__artist').filter(record__isnull=False):
        item.title = item.record.title
        item.artist = item.record.artist.name if item.record.artist else ''
        item.cover_image_url = item.record.cover_image_url
        item.save(update_fields=['title', 'artist', 'cover_image_url'])
    for sale in Sale.objects.prefetch_related('items'):
        sale.final_sale_price = sum((i.price * i.quantity for i in sale.items.all()), Decimal('0.00'))
        sale.save(update_fields=['final_sale_price'])


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0049_owners_and_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='final_sale_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='artist',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cover_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(backfill_existing_sales, migrations.RunPython.noop),
    ]
