# Generated by Django 5.2.1 on 2026-09-29 08:36

from django.db import migrations


def rename_permission(apps, schema_editor):
    """Django creates missing permissions after migrate but never renames
    existing ones: keep the stored name in sync with the new tab label."""
    Permission = apps.get_model('auth', 'Permission')
    Permission.objects.filter(
        content_type__app_label='apiApp', codename='tab_manage_records',
    ).update(name='Ver pestaña Punto de venta')


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0050_sale_payment_commission'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('access_admin_panel', 'Acceder a Administración'), ('tab_add_record', 'Ver pestaña Agregar disco'), ('tab_manage_records', 'Ver pestaña Punto de venta'), ('tab_manage_bazares', 'Ver pestaña Manejo de bazares'), ('tab_manage_orders', 'Ver pestaña Pedidos'), ('tab_sales', 'Ver pestaña Ventas'), ('tab_manage_users', 'Ver pestaña Gestionar usuarios')]},
        ),
        migrations.RunPython(rename_permission, migrations.RunPython.noop),
    ]
