# Generated by Django 5.2.1 on 2026-09-30 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0051_rename_tab_punto_de_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='apiApp.artist'),
        ),
    ]
