# Generated by Django 5.2.1 on 2026-10-01 18:17

import django.db.models.deletion
from django.db import migrations, models


def owner_to_owner_stock(apps, schema_editor):
    """Each record with an owner: that owner has the whole stock. Order lines
    get the owner their record has now (what Ventas → Métricas used so far)."""
    Record = apps.get_model('apiApp', 'Record')
    RecordOwner = apps.get_model('apiApp', 'RecordOwner')
    OrderItem = apps.get_model('apiApp', 'OrderItem')
    RecordOwner.objects.bulk_create(
        RecordOwner(record_id=record.id, owner_id=record.owner_id, quantity=record.stock)
        for record in Record.objects.filter(owner__isnull=False)
    )
    for item in OrderItem.objects.filter(record__owner__isnull=False).select_related('record'):
        item.owner_id = item.record.owner_id
        item.save(update_fields=['owner'])


def owner_stock_to_owner(apps, schema_editor):
    """Reverse: a record goes back to its oldest owner (one owner per record)."""
    Record = apps.get_model('apiApp', 'Record')
    RecordOwner = apps.get_model('apiApp', 'RecordOwner')
    for row in RecordOwner.objects.order_by('-created_at', '-id'):
        # Newest first, so the oldest owner is written last and wins.
        Record.objects.filter(pk=row.record_id).update(owner_id=row.owner_id)


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0052_alter_record_artist_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='apiApp.owner'),
        ),
        migrations.CreateModel(
            name='RecordOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_stock', to='apiApp.owner')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_stock', to='apiApp.record')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('record', 'owner'), name='unique_record_owner')],
            },
        ),
        # Copy before Record.owner is dropped (and after it's re-added on reverse).
        migrations.RunPython(owner_to_owner_stock, owner_stock_to_owner),
        migrations.RemoveField(
            model_name='record',
            name='owner',
        ),
    ]
