from django.urls import path
from .views import (
    record_list,
    record_detail,
    get_category_list,
    get_category_detail,
    add_to_cart,
    update_cart_quantity,
    remove_cart_item,
    get_cart,
    get_all_carts,
    get_all_cart_items,
    remove_all_cart_items,
    add_to_wishlist,
    get_all_wishlists,
    get_wishlist,
    remove_from_wishlist,
    get_wishlist_count,
    add_review,
)

urlpatterns = [
    path('records/', record_list, name='records-list'),
    path('records/<slug:slug>/', record_detail, name='product-detail'),
    path('categories/', get_category_list, name='category-list'),
    path('categories/<slug:slug>/', get_category_detail, name='category-detail'),
    path('cart-items/', get_all_cart_items, name='get-all-cart-items'),
    path('carts/', get_all_carts, name='get-all-carts'),
    path('cart/add/', add_to_cart, name='add-to-cart'),
    path('cart/update/', update_cart_quantity, name='update-cart-quantity'),
    path('cart/remove/', remove_cart_item, name='remove-cart-item'),
    path('cart/remove-all/', remove_all_cart_items, name='remove-all-cart-items'),
    path('cart/<str:cart_code>/', get_cart, name='get-cart'),
    path('wishlists/add/', add_to_wishlist, name='add-to-wishlist'),
    path('wishlists/', get_all_wishlists, name='get-all-wishlists'),
    path('wishlists/<uuid:wishlist_code>/', get_wishlist, name='get-wishlist'),
    path('wishlists/remove/', remove_from_wishlist, name='remove-from-wishlist'),
    path('wishlists/count/', get_wishlist_count, name='get-wishlist-count'),
    path('reviews/add/', add_review, name='add-review'),
]
