"""
Django settings for bemoctezuna_recordsAPI project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv

# override=True locally so .env beats values inherited from a parent process
# (runserver's autoreload child inherits the parent's env — without this, .env
# edits never reach the reloaded server). Under `railway run` /
# RAILWAY_ENVIRONMENT, keep Railway-injected vars authoritative instead.
load_dotenv(override=not os.getenv('RAILWAY_ENVIRONMENT'))
# Local overrides (dev/staging) — gitignored, wins over .env. No-op when absent.
# Skipped when RAILWAY_ENVIRONMENT is set (deployed services AND `railway run`
# both set it) so CLI commands like `railway run python manage.py migrate`
# always target the PROD database instead of silently hitting the local one.
if not os.getenv('RAILWAY_ENVIRONMENT'):
    load_dotenv(".env.local", override=True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "bemoctezuma-records-production.up.railway.app",
    "moctezumarecords.com",
    "www.moctezumarecords.com",
    "api.moctezumarecords.com",
    "http://localhost:5173"
]

CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.app",
    "https://*.ngrok.app",
    "https://karolyn-smokiest-cloyingly.ngrok-free.dev",
    "https://moctezumarecords.com",
    "https://www.moctezumarecords.com",
    "https://api.moctezumarecords.com",
    "https://fe-mocetzuma-records.vercel.app",
    "https://fe-moctezuma-records.vercel.app",
    "https://fe-mocetzuma-records-fecraqq6d-whoisbetos-projects.vercel.app",
]

# CORS: allow frontend origins to call the API
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://moctezumarecords.com",
    "https://www.moctezumarecords.com",
    "https://api.moctezumarecords.com",
    "https://fe-mocetzuma-records-fecraqq6d-whoisbetos-projects.vercel.app",
    "https://fe-moctezuma-records.vercel.app",
    "https://fe-mocetzuma-records.vercel.app",
]
CORS_ALLOW_CREDENTIALS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apiApp',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt'
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'password_reset_request': '10/hour',
        'password_reset_confirm': '30/hour',
        'email_verify': '10/hour',
    },
    'EXCEPTION_HANDLER': 'apiApp.exception_handler.normalized_exception_handler',
}

# JWT lifetimes (long-lived access/refresh tokens)
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=365),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bemoctezuna_recordsAPI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bemoctezuna_recordsAPI.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DB = os.getenv('DB')

if not DB: 
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',    
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('PG_DB'),
            'HOST': os.getenv('PG_HOST'),
            'PORT': os.getenv('PG_PORT'),
            'USER': os.getenv('PG_USER'),
            'PASSWORD': os.getenv('PG_PASSWORD'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Password reset token validity window (matches the "expira en 24 horas" email copy)
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

APPEND_SLASH = False 


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    # Required for file uploads (e.g. Bazar images): Django 5.2 needs an
    # explicit "default" storage; without it any upload raises
    # InvalidStorageError.
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'apiApp.User'
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET') or os.getenv('WEBHOOK_SECRET')
WEBHOOK_SECRET = STRIPE_WEBHOOK_SECRET
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

# Email verification: set to True to block login until the email is verified.
REQUIRE_EMAIL_VERIFICATION = os.getenv('REQUIRE_EMAIL_VERIFICATION', 'False').lower() == 'true'

DISCOGS_TOKEN = os.getenv('DISCOGS_TOKEN', '')

# Envíos Perros (delivery quotes/labels). Same token works for staging and prod;
# ENVIOS_PERROS_API_URL decides the environment:
#   staging: https://staging-app.enviosperros.com/api/v3
#   prod:    https://app.enviosperros.com/api/v3
ENVIOS_PERROS_TOKEN = os.getenv('ENVIOS_PERROS_TOKEN', '').strip()
ENVIOS_PERROS_API_URL = os.getenv(
    'ENVIOS_PERROS_API_URL', 'https://staging-app.enviosperros.com/api/v3'
).strip().rstrip('/')
ORIGIN_ZIP_CODE = os.getenv('ORIGIN_ZIP_CODE', '15400')
# Outbound timeout (seconds) — keep small so checkout never hangs on a slow
# courier API (same lesson as EMAIL_TIMEOUT).
ENVIOS_PERROS_TIMEOUT = int(os.getenv('ENVIOS_PERROS_TIMEOUT', '10'))

# Who gets a notification when a customer places an order (comma-separated env).
SELLER_NOTIFY_EMAILS = [
    email.strip()
    for email in os.getenv(
        'SELLER_NOTIFY_EMAILS',
        'moctezumarecords0@gmail.com,whoisbeto@gmail.com',
    ).split(',')
    if email.strip()
]

# Email (defaults to console backend; use env to override in prod)
# Railway blocks outbound SMTP (see CONTEXT.md), so prod sends via the
# Resend HTTP API through django-anymail whenever RESEND_API_KEY is present.
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND') or (
    'anymail.backends.resend.EmailBackend'
    if os.getenv('RESEND_API_KEY')
    else 'django.core.mail.backends.console.EmailBackend'
)
ANYMAIL = {
    'RESEND_API_KEY': os.getenv('RESEND_API_KEY'),
}
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@moctezumarecords.com')
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
# Cap SMTP attempts so a hung/unreachable mail server raises (and is caught by
# the view-level try/except) instead of blocking a gunicorn worker until the
# request timeout kills it — which surfaced as 500s on /auth/register/.
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '10'))